[tool.uv.workspace]
members = [
    "apps/*",
    "libs/*",
]

[tool.uv.sources]
my-bakery = { workspace = true }
flowershop = { workspace = true }
pos-system = { workspace = true }
project-testing-tools = { workspace = true }

[dependency-groups]
dev = [
    "ruff~=0.15.0"
]
apps = [
    "my-bakery",
    "flowershop",
]
libs = [
    "project-testing-tools",
    "pos-system",
]
